use std::fs;
use std::path::{Path, PathBuf};
use std::io::Write;

mod codegen;

fn main() {
    // Re-run if source changes
    println!("cargo:rerun-if-changed=src/program");

    // Auto-discover and codegen from rosy_test_raw annotations in all source dirs
    let stmt_tests = codegen::discover_and_codegen_annotated(
        Path::new("src/program/statements"),
        "statements",
    );
    let expr_tests = codegen::discover_and_codegen_annotated(
        Path::new("src/program/expressions"),
        "expressions",
    );

    // Generate combined docs for rustdoc inclusion
    codegen::generate_combined_docs("statements", &stmt_tests);
    codegen::generate_combined_docs("expressions", &expr_tests);

    // Generate the annotated test runner (include!'d in test module)
    codegen::generate_annotated_test_runner(&[
        ("statements", &stmt_tests),
        ("expressions", &expr_tests),
    ]);

    println!(
        "cargo:warning=Codegen complete: {} statements + {} expressions = {} total",
        stmt_tests.len(),
        expr_tests.len(),
        stmt_tests.len() + expr_tests.len()
    );

    // Generate the embedded files at compile time
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("embedded_rosy_lib.rs");
    let mut f = fs::File::create(&dest_path).unwrap();

    writeln!(f, "// Auto-generated by build.rs - do not edit manually!").unwrap();
    writeln!(f, "").unwrap();
    writeln!(f, "pub struct EmbeddedFile {{").unwrap();
    writeln!(f, "    pub path: &'static str,").unwrap();
    writeln!(f, "    pub content: &'static str,").unwrap();
    writeln!(f, "}}").unwrap();
    writeln!(f, "").unwrap();
    writeln!(f, "pub const ROSY_LIB_FILES: &[EmbeddedFile] = &[").unwrap();

    // Walk the rosy_lib directory
    let lib_path = PathBuf::from("src/rosy_lib");
    let files = collect_files(&lib_path, &lib_path);

    let file_count = files.len();

    for file in files {
        let full_path = lib_path.join(&file);
        writeln!(f, "    EmbeddedFile {{").unwrap();
        writeln!(f, "        path: r#\"{}\"#,", file.display()).unwrap();
        writeln!(f, "        content: include_str!(r#\"{}\"#),",
            full_path.canonicalize().unwrap().display()).unwrap();
        writeln!(f, "    }},").unwrap();
    }

    writeln!(f, "];").unwrap();

    println!("cargo:warning=Embedded {} rosy_lib files", file_count);
}

fn collect_files(root: &Path, current: &Path) -> Vec<PathBuf> {
    let mut files = Vec::new();

    if let Ok(entries) = fs::read_dir(current) {
        for entry in entries.flatten() {
            let path = entry.path();

            // Skip target directory
            if path.file_name().map_or(false, |n| n == "target") {
                continue;
            }

            if path.is_dir() {
                files.extend(collect_files(root, &path));
            } else if path.is_file() {
                // Include .rs, .rosy, .fox, and .md files
                if let Some(ext) = path.extension() {
                    if ext == "rs" || ext == "rosy" || ext == "fox" || ext == "md" {
                        if let Ok(relative) = path.strip_prefix(root) {
                            files.push(relative.to_path_buf());
                        }
                    }
                }
            }
        }
    }

    files.sort();
    files
}
