use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

fn main() {
    // Check if CodeGraph is initialized
    if !Path::new("../.codegraph").exists() {
        println!("cargo:warning=CodeGraph is not initialized. For faster code exploration, run:");
        println!("cargo:warning=  bunx @colbymchenry/codegraph");
        println!("cargo:warning=  codegraph init");
        println!("cargo:warning=  codegraph index");
    }

    // Emit build timestamp (UTC) as a compile-time env var
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_secs();
    // Format as a human-readable UTC timestamp without pulling in chrono
    let secs = now;
    let days_since_epoch = secs / 86400;
    let time_of_day = secs % 86400;
    let hours = time_of_day / 3600;
    let minutes = (time_of_day % 3600) / 60;
    let seconds = time_of_day % 60;

    // Compute year/month/day from days since 1970-01-01 (civil calendar algorithm)
    let z = days_since_epoch as i64 + 719468;
    let era = z / 146097;
    let doe = z - era * 146097;
    let yoe = (doe - doe / 1460 + doe / 36524 - doe / 146096) / 365;
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let m = if mp < 10 { mp + 3 } else { mp - 9 };
    let y = if m <= 2 { y + 1 } else { y };

    let timestamp = format!(
        "{:04}-{:02}-{:02} {:02}:{:02}:{:02} UTC",
        y, m, d, hours, minutes, seconds
    );
    println!("cargo:rustc-env=BUILD_TIMESTAMP={}", timestamp);

    // Re-run if source changes
    println!("cargo:rerun-if-changed=src/program");
    println!("cargo:rerun-if-changed=src/rosy_lib");

    // Generate the embedded files at compile time
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("embedded_rosy_lib.rs");
    let mut f = fs::File::create(&dest_path).unwrap();

    writeln!(f, "// Auto-generated by build.rs - do not edit manually!").unwrap();
    writeln!(f, "").unwrap();
    writeln!(f, "pub struct EmbeddedFile {{").unwrap();
    writeln!(f, "    pub path: &'static str,").unwrap();
    writeln!(f, "    pub content: &'static str,").unwrap();
    writeln!(f, "}}").unwrap();
    writeln!(f, "").unwrap();
    writeln!(f, "pub const ROSY_LIB_FILES: &[EmbeddedFile] = &[").unwrap();

    // Walk the rosy_lib directory
    let lib_path = PathBuf::from("src/rosy_lib");
    let files = collect_files(&lib_path, &lib_path);

    let _file_count = files.len();

    for file in files {
        let full_path = lib_path.join(&file);
        writeln!(f, "    EmbeddedFile {{").unwrap();
        writeln!(f, "        path: r#\"{}\"#,", file.display()).unwrap();
        writeln!(
            f,
            "        content: include_str!(r#\"{}\"#),",
            full_path.canonicalize().unwrap().display()
        )
        .unwrap();
        writeln!(f, "    }},").unwrap();
    }

    writeln!(f, "];").unwrap();
}

fn collect_files(root: &Path, current: &Path) -> Vec<PathBuf> {
    let mut files = Vec::new();

    if let Ok(entries) = fs::read_dir(current) {
        for entry in entries.flatten() {
            let path = entry.path();

            // Skip target directory
            if path.file_name().map_or(false, |n| n == "target") {
                continue;
            }

            if path.is_dir() {
                files.extend(collect_files(root, &path));
            } else if path.is_file() {
                // Include .rs, .rosy, .fox, and .md files
                if let Some(ext) = path.extension() {
                    if ext == "rs" || ext == "rosy" || ext == "fox" || ext == "md" {
                        if let Ok(relative) = path.strip_prefix(root) {
                            files.push(relative.to_path_buf());
                        }
                    }
                }
            }
        }
    }

    files.sort();
    files
}
