//! Build-time code generation from construct test directories.
//!
//! Walks source directories for construct folders containing `test.rosy` and
//! `test.fox` files and generates:
//! - Test runner (`annotated_tests.rs`) with per-construct `#[test]` functions

use std::fs;
use std::path::{Path, PathBuf};

/// A discovered construct test directory.
#[derive(Debug, Clone)]
pub struct ConstructTest {
    /// Name of the construct (directory name)
    pub name: String,
    /// Path to the construct directory relative to the crate root
    pub dir: PathBuf,
}

/// Walk a directory tree, find construct directories containing `test.rosy`
/// and `test.fox`, and return them sorted by name.
pub fn discover_construct_tests(
    base_dir: &Path,
) -> Vec<ConstructTest> {
    let mut results = Vec::new();
    walk_for_construct_tests(base_dir, &mut results);
    results.sort_by(|a, b| a.name.cmp(&b.name));
    results
}

fn walk_for_construct_tests(
    dir: &Path,
    results: &mut Vec<ConstructTest>,
) {
    let mut entries: Vec<_> = fs::read_dir(dir)
        .into_iter()
        .flatten()
        .flatten()
        .collect();
    entries.sort_by_key(|e| e.path());

    for entry in entries {
        let path = entry.path();
        if path.is_dir() {
            let has_test_rosy = path.join("test.rosy").is_file();

            if has_test_rosy {
                let name = path.file_name().unwrap().to_string_lossy().to_string();
                println!("cargo:rerun-if-changed={}", path.join("test.rosy").display());
                if path.join("test.fox").is_file() {
                    println!("cargo:rerun-if-changed={}", path.join("test.fox").display());
                }
                results.push(ConstructTest {
                    name,
                    dir: path.clone(),
                });
            }

            // Continue walking into subdirectories
            walk_for_construct_tests(&path, results);
        }
    }
}

/// Generate the auto-test runner file that will be `include!`-d in
/// the annotated test module.
///
/// Each discovered construct gets its own `#[test]` function that
/// runs the ROSY script and COSY script, captures their outputs,
/// and writes them to `rosy_output.txt` and `cosy_output.txt`.
pub fn generate_test_runner(
    all_tests: &[(&str, &[ConstructTest])],
) {
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("annotated_tests.rs");

    use std::io::Write;
    let mut f = fs::File::create(&dest).unwrap();

    writeln!(f, "// Auto-generated by build.rs - do not edit manually!").unwrap();
    writeln!(f).unwrap();

    let mut total = 0;
    for &(category, ref tests) in all_tests {
        for test in tests.iter() {
            let dir_str = test.dir.display().to_string().replace('\\', "/");
            writeln!(f, "#[test]").unwrap();
            writeln!(f, "fn test_{}_{}() {{", category, test.name).unwrap();
            writeln!(f, "    run_construct_test(\"{}\", \"{}\", \"{}\");",
                category, test.name, dir_str).unwrap();
            writeln!(f, "}}").unwrap();
            writeln!(f).unwrap();
            total += 1;
        }
    }

    println!("cargo:warning=Generated {} construct test functions", total);
}
